### ISSUE TITLE
Price display format error

### ISSUE THREAD

**Issue by coinuser** [cryptoqween/cryptoqween.github.io#10]
Hi,

found that some price (B3/BTC) with 8 decimal 0.00000012 will display as 1.2e-7. Hope this can be fixed thank you!

**Comment by cryptoqween** [comment]
Hi, it's just a scientific notation. You can format it in your frontend.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
