### ISSUE TITLE
CurrentAgg stops after first message

### ISSUE THREAD

**Issue by gal-terra** [cryptoqween/cryptoqween.github.io#12]
Hi, 

I'm trying to use the CurrentAgg socket to get data on multiple symbols. when I'm testing it with 2 symbols (['5~CCCAGG~BTC~USD', '5~CCCAGG~ETH~USD']) it works fine and I keep getting updates. But when I try to subscribe to 65 symbols, I get the first update and that's it. 
Is there any limit/reason for that? 
BTW, if I use the Current socket the updates keep coming. 

Thanks,
Gal

**Comment by cryptoqween** [comment]
Hi, are you still having this problem? 
Max subscription is 5000.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
