### ISSUE TITLE
Two Queries regarding websockets

### ISSUE THREAD

**Issue by GoChartingAdmin** [cryptoqween/cryptoqween.github.io#13]
I have two queries:

1.  Any plans of providing news and order book through websocket?
2.  Certain pairs provide trade data in certain exchange like `["0~Cryptsy~BTC~USD", "0~Bitstamp~BTC~USD"]`  but when I try the same in CCCAGG, I do not get data

OR for example, `5~Bitstamp~BTC~USD`  does not provide any data over the websocket but `2~Bitstamp~BTC~USD` does

OR for example `0~CCCAGG~BTC~USD` does not provide any data over the websocket but `5~CCCAGG~BTC~USD` does

Sample Response:

```
09:11:10.067 websocketMiddleware.js:153 0~CCCAGG~BTC~USD
09:11:10.067 websocketMiddleware.js:153 3~LOADCOMPLETE
```

How do I know which exchange provides trade data and which exchange provides CURRENTAGG data?

Thank you

**Comment by GoChartingAdmin** [comment]
Scratch point # 2.  I just need a response back on point # 1

**Comment by jcuypers** [comment]
I guess this is normal.   the aggregate provides information for all exchanges that have this specific pair.  If you check the response you will see that the aggregate has a field that shows from which exchange the last data came from.  the current doens't have this field.  this has been described in the documentation.

**Comment by cryptoqween** [comment]
Hi GoChartingAdmin

1. Yes, it will be available. 
We have a news API endpoint already, check the docs here:
https://min-api.cryptocompare.com/

**Comment by GoChartingAdmin** [comment]
Thank you. Now eagerly waiting for order book

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
