### ISSUE TITLE
Receiving undocumented flag "0" when subscribed to Current

### ISSUE THREAD

**Issue by dgellow** [cryptoqween/cryptoqween.github.io#14]
Hi,

I notice today that I was receiving messages with a flag value of `0`. I'm subscribed to [Current](https://www.cryptocompare.com/api/#-api-web-socket-current-).

Example of messages:
```
"2~Kraken~BTC~EUR~0~5250.542889769999~82158362.46584696~15840~8c00"
                  ^—— flag

"2~Kraken~BTC~USD~0~3022.9073560299994~56512986.796085~19219~19258.4~18c00"
                  ^—— flag
```

A zero value isn't documented in the API neither in https://github.com/cryptoqween/cryptoqween.github.io/blob/master/streamer/ccc-streamer-utilities.js. Could you please provide some information about it?

**Comment by jcuypers** [comment]
I've noticed the same.  one of the examples are the 24H volume updates etc.  I have only noticed this for kraken until now, but it can be for everything.  In general the documentation could be improved.  some mistakes and in general unclarity.

**Comment by cryptoqween** [comment]
Hi, 

jcuypers is right, it shows volume update. We will add this to the documentation.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
