### ISSUE TITLE
Unsubscribe 'SubRemove' not working

### ISSUE THREAD

**Issue by frankpaap** [cryptoqween/cryptoqween.github.io#15]
I try to unsubscribe but it aint working this is my code.

`const subscription =  ['2~' + exchange + '~' + coin + '~' + valuta];
    console.log(subscription)
    this._socket.emit('SubRemove', subscription,function(res){
      console.log(res)
    });`

Someon can help me?

**Comment by jcuypers** [comment]
I have the same problem with socketIO implementation for android/java.  All the rest is working fine. I have tried many variants of the SubRemove, but nothing works.  some return 401-BADFORMAT as the format is obviously not correct but the one the should work doesn't return an error but also doesn't work.  Anyone has an example that shows the format required?   Ive already sent a question to CryptoCompare but no response yet.

**Comment by jcuypers** [comment]
BTW i think you need the "subs" as name in front of the subscription array (as with the SubAdd) function.  If you would check the output without it you should normally get 401-badformat

**Comment by TimeTravelersHackedMe** [comment]
Same problem...

**Comment by AndreyArhipov** [comment]
hello!! how to add other exchanges for this sample? such as Binance, OKEx ....

**Comment by cryptoqween** [comment]
This bug is now fixed, let me know if you still have problems.

**Comment by AndreyArhipov** [comment]
How can I write data to a file on PHP ? and can I track the order book from all exchanges in one window?

**Comment by cryptoqween** [comment]
Orderbooks are not available yet.
I don't know PHP myself so can't help with that.

**Comment by AndreyArhipov** [comment]
when will Orderbooks?
