### ISSUE TITLE
What is the max symbols allowed with the WS

### ISSUE THREAD

**Issue by Paul-Thompson54** [cryptoqween/cryptoqween.github.io#16]
I know its beens a while since you posted this but I was wondering would you know the max amount of symbols allowed to be streamed? 

Cheers

**Comment by cryptoqween** [comment]
5000 subscriptions

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
