### ISSUE TITLE
new Markets ....

### ISSUE THREAD

**Issue by AndreyArhipov** [cryptoqween/cryptoqween.github.io#18]
hello!! how to add other exchanges for this sample? such as Binance, OKEx ....

**Comment by cryptoqween** [comment]
You can check the name of all exchanges we have at 
https://min-api.cryptocompare.com/data/all/exchanges

Generally, new documentations is here
https://min-api.cryptocompare.com/

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
