### ISSUE TITLE
missing trivial information in streamer vs polling

### ISSUE THREAD

**Issue by jcuypers** [cryptoqween/cryptoqween.github.io#23]
It seems that some  information is only available through polling and not streaming.  examples of these include  day open (let's say UTC+0) and change since open.   If we could fetch these similar to the 1h/24h variants that would be great and avoids us the polling.  any chance of this being added?

**Comment by cryptoqween** [comment]
We do have day open on the current streaming, change since open can be calculated.
See example:
https://cryptoqween.github.io/streamer/current/

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
