### ISSUE TITLE
Not able to get data with websocket 

### ISSUE THREAD

**Issue by imobdevtech** [cryptoqween/cryptoqween.github.io#24]
Hello 
I try to get current stream data with below code but got nothing in response. 
Here is my code
```

static let sharedInstance = SocketIOManager()

//    let socketManager = SocketManager(socketURL: URL(string: "https://streamer.cryptocompare.com/")!, config: [.log(true),.forceWebsockets(true),.compress])
    let socketManager = SocketManager(socketURL: URL(string: "https://streamer.cryptocompare.com/")!, config: [.log(true)])

    var socket : SocketIOClient!
    override init() {
        super.init()
        socket = socketManager.defaultSocket
        
        socket.onAny {
            print("Any Got event: \($0.event), with items: \($0.items!)")
            
        }

        socket.on("m") { dataArray, ack in
            
            let subscription = ["5~CCCAGG~BTC~USD"];
            self.socket.emitWithAck("SubAdd", subscription).timingOut(after: 0) {data in
                self.socket.emit("SubAdd", subscription)
            }
        }
        socket.connect()

    }
    
```

**System infomation**
Swift ver : 3.0
Xcode ver : 9.2

**Comment by imobdevtech** [comment]
Find the solution from this [link](https://github.com/socketio/socket.io-client-swift/issues/727)

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
