### ISSUE TITLE
timestamp format clarification

### ISSUE THREAD

**Issue by jcuypers** [cryptoqween/cryptoqween.github.io#25]
Update documentation to clarify that timestamp is in epoch seconds and not epoch milliseconds

**Comment by vcealicu** [comment]
correct, seconds not milliseconds.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
