### ISSUE TITLE
Socket drops connection after a white and does not allow to reconnect

### ISSUE THREAD

**Issue by sammyaxe** [cryptoqween/cryptoqween.github.io#27]
Socket drops connection after a while and does not allow to reconnect. Anyone has similar issue?

**Comment by slidenerd** [comment]
I double this issue, just faced it

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
