### ISSUE TITLE
incorrect currency symbol in multiple symbols full data

### ISSUE THREAD

**Issue by cdRigie** [cryptoqween/cryptoqween.github.io#28]
Good day!

i just noticed that the the to and from symbol for this command:
"https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=XRP"
is using the symbol of ethereum. i'm not sure about the rest but you could check it.

i hope you could fix this.

**Comment by cdRigie** [comment]
this command is doing the same thing.
https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=NEO

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
