### ISSUE TITLE
Missing data points

### ISSUE THREAD

**Issue by RohanKapurDEV** [cryptoqween/cryptoqween.github.io#32]
When calling the REST API on the 'Multiple Syms Full Data' endpoint with currencies like EOS, certain entries such as 'SUPPLY' and 'MKTCAP' seem to return 0 as the value. Any chance this is being fixed soon.

Thanks,
Rohan

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
