### ISSUE TITLE
Chrome crashing suddenly

### ISSUE THREAD

**Issue by hlalibe** [cryptoqween/cryptoqween.github.io#33]
Hello,

been using your script for a week or two without problems under windows and Chrome. Suddenly earlier this week Chrome is crashing without any error message. It seems memory usage is pretty high before crashing, could be the cause, but not entirely sure. 

When I run the same script under Internet Explorer, it seems fine, memory usage is much lower. Only problem is that I added a few lines to download a file automatically but that part of mine does not work under IE, not sure why. But this is not why i'm posting as this is my code.

Just wondering if others run it under Chrome without problem recently.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
