### ISSUE TITLE
using several git programs simultaneously

### ISSUE THREAD

**Issue by AtomicNess123** [cryptoqween/cryptoqween.github.io#34]
I have a question of a basic nature that no tutorial has been able to answer to me. I was working with SourceTree in a local repo pushing to Github.com. At some point I decided to use Github Desktop, so I added the local repo and started to push to Github.com. I did not like this software, so I went back to SourceTree. Opened my project there but changes were not being tracked anymore. I wonder if one can use two git managers for tracking changes or else I don't know what went wrong.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
