### ISSUE TITLE
401~MAX_SUBS_REACHED_MAX_5000

### ISSUE THREAD

**Issue by petrovalex** [cryptoqween/cryptoqween.github.io#4]
Hello, 

I am getting this message recently quite often. From client perspective, I do not invoke that many many subscriptions, what this metric is about?

Thanks.

**Comment by vcealicu** [comment]
If you get the max subs reached it means you have tried to subscribe to over 5k symbols / pairs / messages.

If you email me v@cryptocompare.com I can look over your code and I can try to help. Alternatively, you can debug it by just hitting https://streamer.cryptocompare.com/status on the machine you are running the code on and see the number of subs you have registered on the server.

**Comment by cryptoqween** [comment]
Hi there,
just wanted to let you know that this version of the streaming API is being sunset in the next couple of weeks as we are moving to version 2, that has a lot more features and better support. Please visit our documentation page which provides code examples in javascript, node, python and golang: https://min-api.cryptocompare.com/documentation/websockets.
